// Released under an MIT license. See LICENSE.

package task

var symbols = []string{
	"...", "abs", "add", "and", "append", "_append_stderr_",
	"_append_stdout_", "arg", "_args_", "args", "_backtick_", "basename",
	"block", "body", "boolean", "builtin", "catch", "cell", "channel",
	"_channel_stderr_", "_channel_stdout_", "child", "clause", "clone",
	"close", "closer", "cmd", "condition", "conduit", "_connect_",
	"cons", "context", "debug", "define", "dirs", "div", "echo", "else",
	"_env_", "error", "eval", "eval-list", "exists", "exit", "false",
	"fatal", "fifo", "fifos", "file", "first", "float", "for",
	"get-line-number", "get-prompt", "_get_", "glob", "handler", "has",
	"HOME", "import", "integer", "interpolate", "is-atom", "is-boolean",
	"is-builtin", "is-channel", "is-cons", "is-continuation", "is-float",
	"is-integer", "is-method", "is-null", "is-number", "is-object",
	"is-pipe", "is-rational", "is-status", "is-string", "is-symbol",
	"is-syntax", "is-text", "jobs", "join", "last", "left", "length",
	"line", "list", "lst", "match", "message", "method", "mod", "mode",
	"module", "mul", "name", "not", "object", "OHPATH", ".ohrc", "open",
	"_origin_", "PATH", "path", "paths", "pipe", "_pipe_stderr_",
	"_pipe_stdout_", "_platform_", "printf", "proc",
	"_process_substitution_", "procs", "prompt", "public", "PWD",
	"quasiquote", "quote", "rational", "read", "_reader_close_",
	"readline", "readlist", "_redirect_", "_redirect_stderr_",
	"_redirect_stdin_", "_redirect_stdout_", "rest", "_return", "return",
	"reverse", "right", "_root_", "run", "rval", "self", "set",
	"set-line-number", "set-source-file", "_set_", "source", "spawn",
	"_splice_", "split", "sprintf", "status", "_stderr_", "_stdin_",
	"_stdout_", "strict", "string", "sub", "suffix", "symbol", "syntax",
	"_sys_", "temp-fifo", "_throw", "throw", "to-string", "to-symbol",
	"true", "type", "unquote", "USER", "wait", "while", "write",
	"_writer_close_",
}
