linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - paralleltest
    - scopelint
    - wrapcheck

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 96
    statements: 64

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
