// Released under an MIT-style license. See LICENSE.

package common

var Symbols = []string{
	"...", "abs", "add", "and", "append", "_append_stderr_",
	"_append_stdout_", "arg", "_args_", "args", "_backtick_",
	"basename", "block", "body", "boolean", "builtin", "caaaar",
	"caaadr", "caaar", "caadar", "caaddr", "caadr", "caar", "cadaar",
	"cadadr", "cadar", "caddar", "cadddr", "caddr", "cadr", "car",
	"catch", "cdaaar", "cdaadr", "cdaar", "cdadar", "cdaddr", "cdadr",
	"cdar", "cddaar", "cddadr", "cddar", "cdddar", "cddddr", "cdddr",
	"cddr", "cdr", "cell", "channel", "_channel_stderr_",
	"_channel_stdout_", "child", "clause", "clone", "close", "closer",
	"cmd", "condition", "conduit", "_connect_", "cons", "context",
	"$PWD", "debug", "define", "dirs", "div", "echo", "else", "_env_",
	"error", "eval", "eval-list", "exists", "exit", "false", "fatal",
	"fifo", "fifos", "file", "first", "float", "for", "get-line-number",
	"get-prompt", "get-slot", "glob", "handler", "has", "$HOME",
	"import", "integer", "interpolate", "is-atom", "is-boolean",
	"is-builtin", "is-channel", "is-cons", "is-continuation",
	"is-float", "is-integer", "is-list", "is-method", "is-null",
	"is-number", "is-object", "is-pipe", "is-rational", "is-status",
	"is-string", "is-symbol", "is-syntax", "is-text", "jobs", "join",
	"last", "left", "length", "line", "list", "list-ref", "list-tail",
	"list-to-string", "list-to-symbol", "lst", "match", "message",
	"method", "mod", "mode", "module", "mul", "name", "not", "object",
	"$OHPATH", ".ohrc", "open", "_origin_", "$PATH", "path", "paths",
	"pipe", "_pipe_stderr_", "_pipe_stdout_", "_platform_", "printf",
	"proc", "_process_substitution_", "procs", "prompt", "public",
	"quasiquote", "quote", "rational", "read", "_reader_close_",
	"readline", "_redirect_", "_redirect_stderr_", "_redirect_stdin_",
	"_redirect_stdout_", "rest", "_return", "return", "reverse", "right",
	"_root_", "run", "rval", "self", "set", "set-car", "set-cdr",
	"set-line-number", "set-slot", "source", "spawn", "_splice_",
	"split", "sprintf", "status", "_stderr_", "_stdin_", "_stdout_",
	"strict", "string", "sub", "suffix", "symbol", "syntax", "_sys_",
	"temp-fifo", "_throw", "throw", "true", "type", "unquote", "$USER",
	"wait", "while", "write", "_writer_close_",
}
