// Released under an MIT-style license. See LICENSE.

package common

var Symbols = []string{
	"$*", "...", "abs", "add", "and", "append", "append-stderr",
	"append-stdout", "apply", "arg", "args", "backtick",
	"basename", "block", "body", "boolean", "builtin", "caaaar",
	"caaadr", "caaar", "caadar", "caaddr", "caadr", "caar", "cadaar",
	"cadadr", "cadar", "caddar", "cadddr", "caddr", "cadr", "car",
	"catch", "cdaaar", "cdaadr", "cdaar", "cdadar", "cdaddr", "cdadr",
	"cdar", "cddaar", "cddadr", "cddar", "cdddar", "cddddr", "cdddr",
	"cddr", "cdr", "cell", "channel", "channel-stderr",
	"channel-stdout", "child", "clause", "clone", "close", "closer",
	"cmd", "condition", "conduit", "_connect_", "cons", "context",
	"$CWD", "debug", "define", "dirs", "div", "echo", "else", "_env_",
	"error", "eval", "eval-list", "exists", "exit", "false", "fatal",
	"fifo", "fifos", "file", "first", "float", "for", "get-line-number",
	"get-prompt", "get-slot", "glob", "handler", "has", "$HOME",
	"import", "integer", "interpolate", "is-atom", "is-boolean",
	"is-builtin", "is-channel", "is-cons", "is-continuation",
	"is-float", "is-integer", "is-list", "is-method", "is-null",
	"is-number", "is-object", "is-pipe", "is-rational", "is-status",
	"is-string", "is-symbol", "is-syntax", "is-text", "jobs", "join",
	"last", "left", "length", "line", "list", "list-ref", "list-tail",
	"list-to-string", "list-to-symbol", "lst", "match", "message",
	"method", "mod", "mode", "module", "mul", "name", "not", "object",
	"$OHPATH", ".ohrc", "open", "_origin_", "$PATH", "path", "paths",
	"pipe", "pipe-stderr", "pipe-stdout", "_platform_", "printf",
	"proc", "process-substitution", "procs", "prompt", "public",
	"quasiquote", "quote", "rational", "read", "reader-close",
	"readline", "_redirect_", "redirect-stderr", "redirect-stdin",
	"redirect-stdout", "rest", "_return", "return", "reverse", "right",
	"_root_", "run", "rval", "self", "set", "set-car", "set-cdr",
	"setenv", "set-line-number", "set-slot", "source", "spawn",
	"splice", "split", "sprintf", "status", "$stderr", "$stdin",
	"$stdout", "strict", "string", "sub", "suffix", "symbol", "syntax",
	"_sys_", "temp-fifo", "_throw", "throw", "true", "type", "unquote",
	"unset", "$USER", "wait", "while", "write", "writer-close",
}
